name: Psalm – Static Analysis for PHP

on: [push, pull_request]

jobs:
  static-analysis:
    name: Run Psalm Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Psalm – Static Analysis for PHP
        uses: psalm/psalm-github-actions@2.3.0
        with:
          security_analysis: true
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
